import { PDFDocument, PDFFont, rgb, StandardFonts } from "pdf-lib"

/**
 * Data for the Cook County Attorney/Representative Authorization form.
 * Matches the fields we capture in FilingAuthorization.
 */
export interface FilingAuthorizationData {
  propertyAddress: string
  propertyCity: string
  propertyState: string
  propertyZip: string
  propertyPin: string
  ownerName: string
  ownerEmail: string
  ownerPhone: string | null
  ownerAddress: string
  ownerCity: string
  ownerState: string
  ownerZip: string
  signedAt: Date
  taxYear?: number
  appealId?: string
}

/**
 * Generate a PDF that approximates the Cook County Attorney/Representative Authorization form.
 * Contains all required fields for staff to use when filing at the county portal.
 */
export async function generateFilingAuthorizationPdf(
  data: FilingAuthorizationData
): Promise<Uint8Array> {
  const doc = await PDFDocument.create()
  const page = doc.addPage([612, 792])
  const font = await doc.embedFont(StandardFonts.Helvetica)
  const fontBold = await doc.embedFont(StandardFonts.HelveticaBold)
  const size = 10
  const margin = 50
  const pageWidth = 612
  const maxWidth = pageWidth - 2 * margin

  let y = 750

  const drawLine = () => {
    page.drawLine({
      start: { x: margin, y },
      end: { x: pageWidth - margin, y },
      thickness: 0.5,
      color: rgb(0.7, 0.7, 0.7),
    })
    y -= 8
  }

  const drawLabel = (label: string) => {
    page.drawText(label, {
      x: margin,
      y,
      size: size - 1,
      font,
      color: rgb(0.4, 0.4, 0.4),
    })
    y -= 12
  }

  const drawValue = (value: string) => {
    const lines = wrapText(value, font, size, maxWidth)
    for (const line of lines) {
      page.drawText(line, {
        x: margin,
        y,
        size,
        font,
        color: rgb(0.1, 0.1, 0.1),
      })
      y -= 14
    }
    y -= 4
  }

  const drawSection = (title: string, entries: Array<[string, string]>) => {
    page.drawText(title, {
      x: margin,
      y,
      size: size + 1,
      font: fontBold,
      color: rgb(0.1, 0.1, 0.1),
    })
    y -= 18

    for (const [label, value] of entries) {
      if (!value) continue
      drawLabel(label)
      drawValue(value)
    }
    y -= 12
  }

  // Title
  page.drawText("Attorney/Representative Authorization", {
    x: margin,
    y,
    size: 14,
    font: fontBold,
    color: rgb(0.1, 0.1, 0.1),
  })
  y -= 24

  page.drawText("Cook County Assessor – Residential Appeal", {
    x: margin,
    y,
    size: size,
    font,
    color: rgb(0.3, 0.3, 0.3),
  })
  y -= 24

  if (data.taxYear) {
    page.drawText(`Tax Year: ${data.taxYear}`, {
      x: margin,
      y,
      size: size,
      font,
      color: rgb(0.3, 0.3, 0.3),
    })
    y -= 20
  }

  drawLine()
  y -= 12

  // Property being appealed
  drawSection("Property Being Appealed", [
    ["Address", `${data.propertyAddress}, ${data.propertyCity} ${data.propertyState} ${data.propertyZip}`],
    ["PIN", data.propertyPin],
  ])

  drawLine()
  y -= 12

  // Property owner / appellant
  drawSection("Property Owner (Appellant)", [
    ["Name", data.ownerName],
    ["Email", data.ownerEmail],
    ["Phone", data.ownerPhone || "—"],
    ["Mailing Address", `${data.ownerAddress}, ${data.ownerCity} ${data.ownerState} ${data.ownerZip}`],
  ])

  drawLine()
  y -= 12

  // Authorization statement
  const authLines = wrapText(
    "I authorize OverTaxed to act as my representative and file this property tax appeal with the Cook County Assessor on my behalf. I certify that I am the property owner or authorized to act for the owner, and that the information provided is accurate.",
    font,
    size,
    maxWidth
  )
  for (const line of authLines) {
    page.drawText(line, {
      x: margin,
      y,
      size,
      font,
      color: rgb(0.1, 0.1, 0.1),
    })
    y -= 14
  }
  y -= 8

  // Signature block
  page.drawText(`Signed electronically: ${data.signedAt.toLocaleString("en-US")}`, {
    x: margin,
    y,
    size: size - 1,
    font,
    color: rgb(0.4, 0.4, 0.4),
  })
  y -= 16

  page.drawText(`Generated by OverTaxed – For use when filing at Cook County portal`, {
    x: margin,
    y,
    size: size - 2,
    font,
    color: rgb(0.5, 0.5, 0.5),
  })

  return doc.save()
}

function wrapText(text: string, font: PDFFont, size: number, maxWidth: number): string[] {
  const words = text.split(/\s+/)
  if (words.length === 0) return [""]
  const lines: string[] = []
  let current = ""
  for (const word of words) {
    const candidate = current ? current + " " + word : word
    const w = font.widthOfTextAtSize(candidate, size)
    if (w > maxWidth && current) {
      lines.push(current)
      current = word
    } else {
      current = candidate
    }
  }
  if (current) lines.push(current)
  return lines
}
