/**
 * OT T2 delivery-evidence — orphaned artifact content quarantine (PURE layer).
 *
 * When bytes may have reached private storage but the binding that would give
 * them meaning did not complete, the only safe action is to WRITE DOWN what we
 * know. This module decides what that durable record contains. It is pure: no
 * database, no storage, no provider, no clock.
 *
 * Three invariants the whole slice rests on:
 *   - deletion is never decided here, or anywhere in this slice. The same
 *     content address may already be bound by another fulfillment, so removing
 *     the object could destroy immutable evidence that someone else owns;
 *   - the EXPECTED content digest is always recorded, including when the upload
 *     outcome was never observed. A digest is what makes a later reconciliation
 *     possible: it lets a garbage collector prove what the object should be
 *     before touching it;
 *   - ambiguity is recorded as ambiguity. `UNKNOWN` is a first-class upload
 *     outcome, never rounded to "probably absent" or "probably present".
 *
 * Every refusal is a bounded, stable, non-PII code, and no input value is ever
 * echoed back in a result.
 */
import {
  isBoundedOpaqueString,
  isValidArtifactSha256,
  isValidPrivateStorageLocator,
  isValidInstant,
} from "@/lib/fulfillment/validation";

/**
 * Why a stored (or possibly stored) object has no binding.
 *
 * Deliberately a closed set: it is persisted, so a free-form provider or
 * exception string must never be able to reach the column.
 */
export type ArtifactOrphanReasonCode =
  /** The upload call threw. The object may or may not have been committed. */
  | "UPLOAD_OUTCOME_UNKNOWN"
  /** Activation was withdrawn after an object was newly created. */
  | "ACTIVATION_WITHDRAWN"
  /** Storage returned a locator that is not the expected content address. */
  | "STORAGE_LOCATOR_MISMATCH"
  /** The read-back of a newly created object failed. */
  | "STORAGE_READ_FAILED"
  /** The read-back disagreed with the generated bytes. */
  | "STORED_BYTES_MISMATCH"
  /** The binding transaction refused with a bounded blocker. */
  | "BIND_REFUSED"
  /** The binding transaction threw; the commit outcome is unknown. */
  | "BIND_OUTCOME_UNKNOWN";

export const ARTIFACT_ORPHAN_REASON_CODES: ReadonlySet<string> =
  new Set<string>([
    "UPLOAD_OUTCOME_UNKNOWN",
    "ACTIVATION_WITHDRAWN",
    "STORAGE_LOCATOR_MISMATCH",
    "STORAGE_READ_FAILED",
    "STORED_BYTES_MISMATCH",
    "BIND_REFUSED",
    "BIND_OUTCOME_UNKNOWN",
  ]);

/**
 * Whether the object is known to exist.
 *
 * `CONFIRMED` means storage returned a trustworthy created result. `UNKNOWN`
 * means the write outcome was never observed — a timeout, a lost response, or a
 * thrown call — and the object may or may not be there.
 */
export type ArtifactOrphanUploadOutcome = "CONFIRMED" | "UNKNOWN";

export const ARTIFACT_ORPHAN_UPLOAD_OUTCOMES: ReadonlySet<string> =
  new Set<string>(["CONFIRMED", "UNKNOWN"]);

export type ArtifactOrphanBlocker =
  | "INVALID_FULFILLMENT_ID"
  | "INVALID_ORDER_ID"
  | "INVALID_STORAGE_LOCATOR"
  | "INVALID_ARTIFACT_SHA256"
  | "INVALID_UPLOAD_OUTCOME"
  | "INVALID_REASON_CODE"
  | "UNTRUSTED_CLOCK";

export const ARTIFACT_ORPHAN_BLOCKERS: ReadonlySet<string> = new Set<string>([
  "INVALID_FULFILLMENT_ID",
  "INVALID_ORDER_ID",
  "INVALID_STORAGE_LOCATOR",
  "INVALID_ARTIFACT_SHA256",
  "INVALID_UPLOAD_OUTCOME",
  "INVALID_REASON_CODE",
  "UNTRUSTED_CLOCK",
]);

export type ArtifactOrphanObservation = {
  fulfillmentId: string;
  sourceOrderId: string;
  /** Where bytes may be. Private internal locator only — never a bearer URL. */
  storageLocator: string;
  /** What those bytes are expected to hash to. Always recorded. */
  artifactSha256: string;
  uploadOutcome: ArtifactOrphanUploadOutcome;
  reasonCode: ArtifactOrphanReasonCode;
  /** Store-owned transaction time as a strict RFC3339 UTC instant. */
  observedAt: string;
};

/** The exact durable identity to persist. Payload-free. */
export type ArtifactOrphanRecord = {
  fulfillmentId: string;
  sourceOrderId: string;
  storageLocator: string;
  artifactSha256: string;
  uploadOutcome: ArtifactOrphanUploadOutcome;
  reasonCode: ArtifactOrphanReasonCode;
  observedAt: string;
};

export type ArtifactOrphanDecision =
  | { ok: true; record: ArtifactOrphanRecord }
  | { ok: false; blocker: ArtifactOrphanBlocker };

/**
 * Validate one orphan observation into a durable record, or refuse with a
 * bounded code.
 *
 * Note what is NOT checked: that the locator is the content address of the
 * digest. When storage hands back an unexpected locator, the bytes are at that
 * unexpected place, and recording where they actually are — alongside what they
 * were expected to be — is the entire point.
 */
export function decideArtifactOrphanRecord(
  observation: ArtifactOrphanObservation,
): ArtifactOrphanDecision {
  if (!isBoundedOpaqueString(observation.fulfillmentId, 128))
    return { ok: false, blocker: "INVALID_FULFILLMENT_ID" };
  if (!isBoundedOpaqueString(observation.sourceOrderId, 128))
    return { ok: false, blocker: "INVALID_ORDER_ID" };
  if (!isValidPrivateStorageLocator(observation.storageLocator))
    return { ok: false, blocker: "INVALID_STORAGE_LOCATOR" };
  if (!isValidArtifactSha256(observation.artifactSha256))
    return { ok: false, blocker: "INVALID_ARTIFACT_SHA256" };
  if (!ARTIFACT_ORPHAN_UPLOAD_OUTCOMES.has(observation.uploadOutcome))
    return { ok: false, blocker: "INVALID_UPLOAD_OUTCOME" };
  if (!ARTIFACT_ORPHAN_REASON_CODES.has(observation.reasonCode))
    return { ok: false, blocker: "INVALID_REASON_CODE" };
  if (!isValidInstant(observation.observedAt))
    return { ok: false, blocker: "UNTRUSTED_CLOCK" };

  return {
    ok: true,
    record: {
      fulfillmentId: observation.fulfillmentId,
      sourceOrderId: observation.sourceOrderId,
      storageLocator: observation.storageLocator,
      artifactSha256: observation.artifactSha256,
      uploadOutcome: observation.uploadOutcome,
      reasonCode: observation.reasonCode,
      observedAt: observation.observedAt,
    },
  };
}
