import "server-only"
import { createHash, randomUUID } from "node:crypto"
import { Prisma } from "@prisma/client"
import { neutralPrisma } from "@/lib/fulfillment-runtime/neutral-db"
import { readNeutralBundle } from "@/lib/fulfillment-runtime/neutral-report-storage"
import { readNeutralCustomerZip,writeNeutralCustomerZip } from "@/lib/fulfillment-runtime/neutral-customer-zip-storage"
import { createNeutralCustomerZip,neutralCustomerZipLocator,neutralCustomerZipSha256,NEUTRAL_CUSTOMER_ZIP_FILENAME,NEUTRAL_CUSTOMER_ZIP_MEDIA_TYPE } from "@/lib/fulfillment/neutral-customer-zip"
import { decideCurrentArtifact,decideNeutralCustomerPromotion,decideZipWriteAction } from "@/lib/fulfillment/neutral-customer-promotion"

type Db={ $queryRaw<T>(q:unknown):Promise<T>; $executeRaw(q:unknown):Promise<number>; $transaction<T>(f:(tx:Db)=>Promise<T>):Promise<T> }
const db=()=>neutralPrisma() as unknown as Db
type Row={reservationId:string;orderId:string;status:string;bundleSha256:string|null;privateReferences:unknown;policyVersion:string;propertyFingerprint:string;dataEvidenceSha256:string;deadlineEvidenceSha256:string;manifestSha256:string|null;supersededBySha256:string|null;orderStatus:string;propertyPin:string|null;sessionId:string|null;paymentIntent:string|null;reversalIntent:string|null;qaOrderId:string|null;qaStatus:string|null;qaArtifactSha256:string|null;qaPolicyVersion:string|null;qaPropertyFingerprint:string|null;qaEvidenceDigestSha256:string|null;qaPaymentBindingSha256:string|null;qaFulfillmentId:string|null;customerZipSha256:string|null;customerZipLocator:string|null}
const query=(orderId:string)=>Prisma.sql`SELECT r."id" "reservationId",r."order_id" "orderId",r."status"::text "status",r."bundle_sha256" "bundleSha256",r."private_references" "privateReferences",r."policy_version" "policyVersion",r."property_fingerprint" "propertyFingerprint",r."data_evidence_sha256" "dataEvidenceSha256",r."deadline_evidence_sha256" "deadlineEvidenceSha256",r."manifest_sha256" "manifestSha256",r."superseded_by_sha256" "supersededBySha256",r."customer_zip_sha256" "customerZipSha256",r."customer_zip_locator" "customerZipLocator",o."status" "orderStatus",o."propertyPin",o."stripeSessionId" "sessionId",b."payment_intent" "paymentIntent",x."payment_intent" "reversalIntent",q."order_id" "qaOrderId",q."status"::text "qaStatus",q."artifact_sha256" "qaArtifactSha256",q."policy_version" "qaPolicyVersion",q."property_binding_fingerprint" "qaPropertyFingerprint",q."evidence_digest_sha256" "qaEvidenceDigestSha256",q."payment_binding_sha256" "qaPaymentBindingSha256",q."fulfillment_id" "qaFulfillmentId" FROM "ot_neutral_report_reservation" r JOIN "ot_order" o ON o."id"=r."order_id" LEFT JOIN "ot_payment_binding" b ON b."order_id"=o."id" AND b."session_id"=o."stripeSessionId" LEFT JOIN "ot_settlement_reversal" x ON x."payment_intent"=b."payment_intent" LEFT JOIN "ot_neutral_qa_review" q ON q."reservation_id"=r."id" WHERE r."order_id"=${orderId}`
async function lockedRow(tx:Db,orderId:string){
  // The neutral runtime has read-only authority over global commerce tables.
  // Serialize this order with an advisory lock, lock only the neutral-owned
  // reservation, then re-read payment/order authority without requiring UPDATE
  // privileges on ot_order or ot_fulfillment.
  await tx.$queryRaw(Prisma.sql`SELECT pg_advisory_xact_lock(hashtext(${`neutral-promotion:${orderId}`}))::text AS "locked"`)
  await tx.$queryRaw(Prisma.sql`SELECT "id" FROM "ot_neutral_report_reservation" WHERE "order_id"=${orderId} FOR UPDATE`)
  return (await tx.$queryRaw<Row[]>(query(orderId)))[0]
}
function locator(v:unknown){if(!v||typeof v!=="object")return null;const x=(v as {locator?:unknown}).locator;return typeof x==="string"?x:null}
const digest=(value:string)=>createHash("sha256").update(value).digest("hex")
const snap=(r:Row)=>({orderStatus:r.orderStatus,paymentIntent:r.paymentIntent,reversalIntent:r.reversalIntent,propertyPin:r.propertyPin,reservationStatus:r.status,bundleSha256:r.bundleSha256,customerZipSha256:r.customerZipSha256,manifestSha256:r.manifestSha256,dataEvidenceSha256:r.dataEvidenceSha256,deadlineEvidenceSha256:r.deadlineEvidenceSha256,policyVersion:r.policyVersion,propertyFingerprint:r.propertyFingerprint,supersededBySha256:r.supersededBySha256,qaStatus:r.qaStatus,qaArtifactSha256:r.qaArtifactSha256,qaPolicyVersion:r.qaPolicyVersion,qaPropertyFingerprint:r.qaPropertyFingerprint,qaEvidenceDigestSha256:r.qaEvidenceDigestSha256,currentEvidenceDigestSha256:digest(`neutral-evidence/v1\0${r.dataEvidenceSha256}\0${r.deadlineEvidenceSha256}\0${r.manifestSha256}`),qaPaymentBindingSha256:r.qaPaymentBindingSha256,currentPaymentBindingSha256:digest(`neutral-payment/v1\0${r.orderId}\0${r.sessionId}\0${r.paymentIntent}`)})
function valid(r:Row|undefined){return !!r&&r.qaOrderId===r.orderId&&!!r.sessionId&&decideNeutralCustomerPromotion(snap(r),snap(r)).ok}

/** Two-transaction promotion. An ambiguous object write is recorded and never blindly retried. */
export async function promoteApprovedNeutralCustomerZip(orderId:string){
 if(process.env.OT_NEUTRAL_CUSTOMER_ZIP_PROMOTION_ENABLED!=="true")return {ok:false as const,blocker:"FLAG_DISABLED"}
 const snapshot=await db().$transaction(async tx=>{const r=await lockedRow(tx,orderId);if(!valid(r))return null;return r!})
 if(!snapshot)return {ok:false as const,blocker:"AUTHORITY_NOT_CURRENT"}
 if(snapshot.customerZipSha256&&snapshot.customerZipLocator)return {ok:true as const,sha256:snapshot.customerZipSha256,created:false}
 const internalLocator=locator(snapshot.privateReferences);if(!internalLocator)return {ok:false as const,blocker:"INTERNAL_BUNDLE_UNAVAILABLE"}
 const bundle=await readNeutralBundle(internalLocator,snapshot.bundleSha256!)
 const bytes=createNeutralCustomerZip({pdf:bundle.pdf,csv:bundle.csv}),sha256=neutralCustomerZipSha256(bytes),storageLocator=neutralCustomerZipLocator(sha256),attemptId=randomUUID()
 await db().$executeRaw(Prisma.sql`INSERT INTO "ot_neutral_customer_zip_attempt"("id","reservation_id","zip_sha256","byte_size","storage_locator","status") VALUES(${attemptId},${snapshot.reservationId},${sha256},${bytes.length},${storageLocator},'INTENDED') ON CONFLICT("reservation_id","zip_sha256") DO NOTHING`)
 const prior=(await db().$queryRaw<Array<{status:string}>>(Prisma.sql`SELECT "status" FROM "ot_neutral_customer_zip_attempt" WHERE "reservation_id"=${snapshot.reservationId} AND "zip_sha256"=${sha256}`))[0]?.status
 const writeAction=decideZipWriteAction(prior)
 if(writeAction==="REFUSE")return {ok:false as const,blocker:"ATTEMPT_STATE_CONFLICT"}
 if(writeAction==="RECONCILE_READ"){
   try{const existing=await readNeutralCustomerZip(storageLocator);if(neutralCustomerZipSha256(existing)!==sha256)return {ok:false as const,blocker:"WRITE_UNKNOWN"};const confirmed=await db().$executeRaw(Prisma.sql`UPDATE "ot_neutral_customer_zip_attempt" SET "status"='READ_CONFIRMED',"reason_code"='OBJECT_READ_CONFIRMED',"observed_at"=clock_timestamp() WHERE "reservation_id"=${snapshot.reservationId} AND "zip_sha256"=${sha256} AND "status"='WRITE_UNKNOWN'`);if(confirmed!==1)return {ok:false as const,blocker:"WRITE_UNKNOWN"}}catch{return {ok:false as const,blocker:"WRITE_UNKNOWN"}}
 }else if(writeAction==="WRITE_ONCE"){
   try{const stored=await writeNeutralCustomerZip(bytes);if(stored.sha256!==sha256||stored.locator!==storageLocator)throw new Error("IDENTITY_MISMATCH");const confirmed=await db().$executeRaw(Prisma.sql`UPDATE "ot_neutral_customer_zip_attempt" SET "status"='WRITE_CONFIRMED',"observed_at"=clock_timestamp() WHERE "reservation_id"=${snapshot.reservationId} AND "zip_sha256"=${sha256} AND "status"='INTENDED'`);if(confirmed!==1)throw new Error("ATTEMPT_CAS_MISS")}catch{await db().$executeRaw(Prisma.sql`UPDATE "ot_neutral_customer_zip_attempt" SET "status"='WRITE_UNKNOWN',"reason_code"='OBJECT_WRITE_UNKNOWN',"observed_at"=clock_timestamp() WHERE "reservation_id"=${snapshot.reservationId} AND "zip_sha256"=${sha256} AND "status"='INTENDED'`);return {ok:false as const,blocker:"WRITE_UNKNOWN"}}
 }
 return db().$transaction(async tx=>{const quarantine=async(blocker:string)=>{const changed=await tx.$executeRaw(Prisma.sql`UPDATE "ot_neutral_customer_zip_attempt" SET "status"='QUARANTINED',"reason_code"=${blocker},"observed_at"=clock_timestamp() WHERE "reservation_id"=${snapshot.reservationId} AND "zip_sha256"=${sha256} AND "status" IN ('INTENDED','WRITE_CONFIRMED','READ_CONFIRMED')`);return {ok:false as const,blocker:changed===1?blocker:"QUARANTINE_CONFLICT"}}
   const r=await lockedRow(tx,orderId);if(!r||r.qaOrderId!==r.orderId||!r.sessionId)return quarantine("AUTHORITY_DRIFT");const authority=decideNeutralCustomerPromotion(snap(snapshot),snap(r));if(!authority.ok)return quarantine(authority.blocker);
   let fulfillmentId=r!.qaFulfillmentId??randomUUID();if(!r!.qaFulfillmentId){await tx.$executeRaw(Prisma.sql`INSERT INTO "ot_fulfillment"("id","order_id","kind","status","updated_at") VALUES(${fulfillmentId},${orderId},'NEUTRAL_RECORDS_REPORT','ARTIFACT_READY',clock_timestamp()) ON CONFLICT("order_id","kind") DO NOTHING`)}
   const fulfillment=(await tx.$queryRaw<Array<{id:string;status:string;attemptCount:number;artifactCount:number}>>(Prisma.sql`SELECT f."id",f."status"::text "status",f."attempt_count" "attemptCount",(SELECT count(*)::int FROM "ot_fulfillment_artifact" a WHERE a."fulfillment_id"=f."id") "artifactCount" FROM "ot_fulfillment" f WHERE f."order_id"=${orderId} AND f."kind"='NEUTRAL_RECORDS_REPORT'`))[0]
   if(!fulfillment||fulfillment.status!=="ARTIFACT_READY"||fulfillment.attemptCount!==0||fulfillment.artifactCount>1|| (r!.qaFulfillmentId!==null&&r!.qaFulfillmentId!==fulfillment.id))return quarantine("FULFILLMENT_CONFLICT");fulfillmentId=fulfillment.id
   const current=(await tx.$queryRaw<Array<{artifactSha256:string;byteSize:number;storageLocator:string;generatorVersion:string;templateVersion:string;sourceOrderId:string;propertyBindingFingerprint:string;version:number}>>(Prisma.sql`SELECT "artifact_sha256" "artifactSha256","byte_size" "byteSize","storage_locator" "storageLocator","generator_version" "generatorVersion","template_version" "templateVersion","source_order_id" "sourceOrderId","property_binding_fingerprint" "propertyBindingFingerprint","version" FROM "ot_fulfillment_artifact" WHERE "fulfillment_id"=${fulfillmentId} ORDER BY "version" DESC LIMIT 1`))[0]
   const artifactDecision=decideCurrentArtifact(current?.artifactSha256,sha256);if(!artifactDecision.ok)return quarantine(artifactDecision.blocker)
   if(current&&(current.version!==1||current.byteSize!==bytes.length||current.storageLocator!==storageLocator||current.generatorVersion!=="neutral-customer-zip/v1"||current.templateVersion!==r!.policyVersion||current.sourceOrderId!==orderId||current.propertyBindingFingerprint!==r!.propertyFingerprint))return quarantine("ARTIFACT_IDENTITY_CONFLICT")
   if(artifactDecision.create)await tx.$executeRaw(Prisma.sql`INSERT INTO "ot_fulfillment_artifact"("id","fulfillment_id","version","artifact_sha256","byte_size","storage_locator","generator_version","template_version","generated_at","source_order_id","property_binding_fingerprint") VALUES(${randomUUID()},${fulfillmentId},1,${sha256},${bytes.length},${storageLocator},'neutral-customer-zip/v1',${r!.policyVersion},clock_timestamp(),${orderId},${r!.propertyFingerprint})`)
   const changed=await tx.$executeRaw(Prisma.sql`UPDATE "ot_neutral_report_reservation" SET "customer_zip_sha256"=${sha256},"customer_zip_byte_size"=${bytes.length},"customer_zip_locator"=${storageLocator},"customer_zip_media_type"=${NEUTRAL_CUSTOMER_ZIP_MEDIA_TYPE},"customer_zip_filename"=${NEUTRAL_CUSTOMER_ZIP_FILENAME},"updated_at"=clock_timestamp() WHERE "id"=${r!.reservationId} AND "customer_zip_sha256" IS NULL`)
   if(changed!==1&&r!.customerZipSha256!==sha256)return quarantine("PROMOTION_CONFLICT");
   const rebound=await tx.$executeRaw(Prisma.sql`UPDATE "ot_neutral_qa_review" SET "fulfillment_id"=${fulfillmentId},"customer_artifact_sha256"=${sha256},"updated_at"=clock_timestamp() WHERE "reservation_id"=${r!.reservationId} AND "order_id"=${r!.orderId} AND "status"='APPROVED' AND "artifact_sha256"=${r!.bundleSha256} AND ("customer_artifact_sha256" IS NULL OR "customer_artifact_sha256"=${sha256}) AND "evidence_digest_sha256"=${r!.qaEvidenceDigestSha256} AND "payment_binding_sha256"=${r!.qaPaymentBindingSha256}`)
   if(rebound!==1)return quarantine("QA_BINDING_DRIFT")
   const promoted=await tx.$executeRaw(Prisma.sql`UPDATE "ot_neutral_customer_zip_attempt" SET "status"='PROMOTED',"observed_at"=clock_timestamp() WHERE "reservation_id"=${r!.reservationId} AND "zip_sha256"=${sha256} AND "status" IN ('WRITE_CONFIRMED','READ_CONFIRMED')`);if(promoted!==1)return quarantine("ATTEMPT_STATE_CONFLICT");return {ok:true as const,sha256,created:true}
 })
}
